spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes[0]:
        id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates[0]: Path= /user/**
      routes[1]:
        id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates[0]: Path= /hotels/**
      routes[2]:
        id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates[0]: Path= /ratings/**



server:
  port: 8089
